### ISSUE TITLE
403 error when I tried to push

### ISSUE THREAD

**Issue by kentemorrison** [active-calculus/active-calculus-single-mbx#27]
Here's what happens. 

% git push origin ww-titles-7.1-3
Username for 'https://github.com': kentemorrison
Password for 'https://kentemorrison@github.com': 
remote: Permission to active-calculus/active-calculus-single-mbx.git denied to kentemorrison.
fatal: unable to access 'https://github.com/active-calculus/active-calculus-single-mbx.git/': The requested URL returned error: 403

**Comment by davidfarmer** [comment]
If you do "git remote -v" you should see something like this,
with davidfarmer replaced by you:

origin	https://github.com/davidfarmer/active-calculus-single-mbx.git 
(fetch)
origin	https://github.com/davidfarmer/active-calculus-single-mbx.git 
(push)
upstream 
https://github.com/active-calculus/active-calculus-single-mbx.git (fetch)
upstream 
https://github.com/active-calculus/active-calculus-single-mbx.git (push)

But what I think you will see is that your origin looks like your 
upstream.

If that is it, it probably is because you cloned from the official 
repository,
not from your fork.

The remedy:

git remote rm origin
git remote add origin [YOUR green button URL]

**Comment by kentemorrison** [comment]
Yes, I had just figured that out. I'm now cloning from my fork.

**Comment by davidfarmer** [comment]
No need to clone again:  just rearrange the remotes.
